### ISSUE TITLE
Quoted text is huge

### ISSUE THREAD

**Issue by DanielSWolf** [Dynalon/mdwiki#195]
I'd expect quoted text to be the same size as regular text. On GitHub, if I write `> A quote`, it looks like this:

> A quote

However, MDWiki renders it like this:

![quote](https://cloud.githubusercontent.com/assets/5963162/6270229/a5d5ce46-b858-11e4-8151-78b8e56c8b94.png)

For some reason, mdwiki.html contains the following CSS code:

```css
blockquote p{font-size:17.5px;font-weight:300;line-height:1.25}
```
