### ISSUE TITLE
<kbd> style

### ISSUE THREAD

**Issue by ttyz** [Dynalon/mdwiki#230]
```<kbd></kbd>``` tag is not working. I think it might be a good idea to add this to the stylesheet:

```css
kbd {
    display: inline-block;
    font-size: 11px;
    line-height: 10px;
    color: #555;
    vertical-align: middle;
    background-color: #fcfcfc;
    border: solid 1px #ccc;
    border-bottom-color: #bbb;
    border-radius: 3px;
    padding: 3px 5px;
    box-shadow: inset 0 -1px 0 #bbb;
}
```
